development:
  url: redis://localhost:6379
  namespace: development_cache
  db: 1

test:
  url: redis://localhost:6379
  namespace: test_cache
  db: 2

production:
  url: <%= ENV['REDIS_URL'] %>
  namespace: production_cache
  db: 0
